import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { GetOperationTypeResults } from "../../types";
import { ReactChild, ReactFragment, ReactPortal } from 'react';

const Home: NextPage = ({ operationType }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {operationType.map((type: any) => <div>{type.name}</div>)}
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  let results: any[] = [];
  const res = await axios.get(`http://localhost:43792/operations/operation-types`)
    .then((response) =>
    {
      results = response.data
    }) 
  return {
    props: {
      operationType: results
    }
  }

  // http://localhost:43792/operations/operation-types
}

export default Home
