import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { OperationType } from "../types";
import Box from '@mui/material/Box';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import Select, { SelectChangeEvent } from '@mui/material/Select';
import DepositTable from '../components/DepositTable';


const Home: NextPage<{ operationType: OperationType[] }> = ({ operationType }) => {
  const handleChange = (event: SelectChangeEvent) => {
    console.log(event.target.value)
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box sx={{ width: 500 }}>
          <FormControl fullWidth>
            <InputLabel id="demo-simple-select-label">Select Any</InputLabel>
            <Select
              labelId="demo-simple-select-label"
              id="demo-simple-select"
              value={operationType[0].id}
              label="Select Any..."
              onChange={handleChange}
            >{operationType.map((type: any) => <MenuItem key={type.id} value={type.id}>{type.name}</MenuItem>)}
            </Select>
          </FormControl>
        </Box>
        <DepositTable />
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  let results: OperationType[] = [];
  await axios.get(`http://localhost:43792/operations/operation-types`)
    .then((response) =>
    {
      results = response.data
    }) 
  return {
    props: {
      operationType: results
    }
  }
}

export default Home
